// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvOgZZ0e5MrlqoKRN86nBWi8DMgz1qVwE',
    appId: '1:345408735696:web:187460f83910d1005811d5',
    messagingSenderId: '345408735696',
    projectId: 'ajir-f4e36',
    authDomain: 'ajir-f4e36.firebaseapp.com',
    storageBucket: 'ajir-f4e36.firebasestorage.app',
    measurementId: 'G-3DDVBM2BK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfVfs8P2FN8wKjnoQaHgLTtJ8MbfsRB8o',
    appId: '1:345408735696:android:83171ba5e077215a5811d5',
    messagingSenderId: '345408735696',
    projectId: 'ajir-f4e36',
    storageBucket: 'ajir-f4e36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADH-it75P-zN-JS4XfpS5DcgW71PFE5vU',
    appId: '1:345408735696:ios:0b2a57232b18c48a5811d5',
    messagingSenderId: '345408735696',
    projectId: 'ajir-f4e36',
    storageBucket: 'ajir-f4e36.firebasestorage.app',
    iosBundleId: 'com.example.ajir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADH-it75P-zN-JS4XfpS5DcgW71PFE5vU',
    appId: '1:345408735696:ios:0b2a57232b18c48a5811d5',
    messagingSenderId: '345408735696',
    projectId: 'ajir-f4e36',
    storageBucket: 'ajir-f4e36.firebasestorage.app',
    iosBundleId: 'com.example.ajir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvOgZZ0e5MrlqoKRN86nBWi8DMgz1qVwE',
    appId: '1:345408735696:web:c09e43a11cc781b05811d5',
    messagingSenderId: '345408735696',
    projectId: 'ajir-f4e36',
    authDomain: 'ajir-f4e36.firebaseapp.com',
    storageBucket: 'ajir-f4e36.firebasestorage.app',
    measurementId: 'G-YJPDDD2TKJ',
  );
}
